/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Publisher } from "./Publisher";
import { PublisherCountArgs } from "./PublisherCountArgs";
import { PublisherFindManyArgs } from "./PublisherFindManyArgs";
import { PublisherFindUniqueArgs } from "./PublisherFindUniqueArgs";
import { DeletePublisherArgs } from "./DeletePublisherArgs";
import { PublisherService } from "../publisher.service";
@graphql.Resolver(() => Publisher)
export class PublisherResolverBase {
  constructor(protected readonly service: PublisherService) {}

  async _publishersMeta(
    @graphql.Args() args: PublisherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Publisher])
  async publishers(
    @graphql.Args() args: PublisherFindManyArgs
  ): Promise<Publisher[]> {
    return this.service.publishers(args);
  }

  @graphql.Query(() => Publisher, { nullable: true })
  async publisher(
    @graphql.Args() args: PublisherFindUniqueArgs
  ): Promise<Publisher | null> {
    const result = await this.service.publisher(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Publisher)
  async deletePublisher(
    @graphql.Args() args: DeletePublisherArgs
  ): Promise<Publisher | null> {
    try {
      return await this.service.deletePublisher(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
